/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-x86_64"
#define DATE "built on: Tue Jul  7 19:44:21 2026 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','m','u','s','l','-','g',
    'c','c',' ','-','f','n','o','-','l','i','n','k','-','l','i','b',
    'a','t','o','m','i','c',' ','-','i','d','i','r','a','f','t','e',
    'r',' ','/','h','o','m','e','/','i','l','d','a','r','/','k','y',
    'r','o','n','i','x','-','p','o','r','t','s','/','l','i','b','s',
    '/','o','p','e','n','s','s','l','/','o','b','j','-','m','u','s',
    'l','/','.','.','/','k','e','r','n','e','l','-','h','e','a','d',
    'e','r','s',' ','-','f','P','I','C',' ','-','p','t','h','r','e',
    'a','d',' ','-','m','6','4',' ','-','W','a',',','-','-','n','o',
    'e','x','e','c','s','t','a','c','k',' ','-','W','a','l','l',' ',
    '-','O','3',' ','-','D','L','_','E','N','D','I','A','N',' ','-',
    'D','O','P','E','N','S','S','L','_','P','I','C',' ','-','D','N',
    'D','E','B','U','G','\0'
};
