/* Generated by ./src/xlat/gen.sh from ./src/xlat/uring_zcrx_ctrl_ops.in; do not edit. */

#include "gcc_compat.h"
#include "static_assert.h"

#undef XLAT_PREV_VAL

#ifndef XLAT_MACROS_ONLY

# ifdef IN_MPERS

#  error static const struct xlat uring_zcrx_ctrl_ops in mpers mode

# else

DIAG_PUSH_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE
static const struct xlat_data uring_zcrx_ctrl_ops_xdata[] = {
 XLAT(ZCRX_CTRL_FLUSH_RQ),
 #define XLAT_VAL_0 ((unsigned) (ZCRX_CTRL_FLUSH_RQ))
 #define XLAT_STR_0 STRINGIFY(ZCRX_CTRL_FLUSH_RQ)
 XLAT(ZCRX_CTRL_EXPORT),
 #define XLAT_VAL_1 ((unsigned) (ZCRX_CTRL_EXPORT))
 #define XLAT_STR_1 STRINGIFY(ZCRX_CTRL_EXPORT)
};
static
const struct xlat uring_zcrx_ctrl_ops[1] = { {
 .data = uring_zcrx_ctrl_ops_xdata,
 .size = ARRAY_SIZE(uring_zcrx_ctrl_ops_xdata),
 .type = XT_NORMAL,
 .flags_mask = 0
#  ifdef XLAT_VAL_0
  | XLAT_VAL_0
#  endif
#  ifdef XLAT_VAL_1
  | XLAT_VAL_1
#  endif
  ,
 .flags_strsz = 0
#  ifdef XLAT_STR_0
  + sizeof(XLAT_STR_0)
#  endif
#  ifdef XLAT_STR_1
  + sizeof(XLAT_STR_1)
#  endif
  ,
} };
DIAG_POP_IGNORE_TAUTOLOGICAL_CONSTANT_COMPARE

#  undef XLAT_STR_0
#  undef XLAT_VAL_0
#  undef XLAT_STR_1
#  undef XLAT_VAL_1
# endif /* !IN_MPERS */

#endif /* !XLAT_MACROS_ONLY */
