# things set by configure

_MAKE_VERSION?=20260619

prefix?= /usr/local
srcdir= /home/ildar/kyronix-ports/tools/bmake
CC= musl-gcc -fno-link-libatomic -static
MAKE_OS?= 
MACHINE?= x86_64
MACHINE_ARCH?= x86_64
DEFAULT_SYS_PATH?= /usr/local/share/mk
MAKE_SAVE_DOLLARS_DEFAULT?= no

EGREP = grep -E
CPPFLAGS+=  -I/home/ildar/kyronix-ports/tools/bmake/missing
CFLAGS+= ${CPPFLAGS} -DHAVE_CONFIG_H
LDFLAGS+= 
LIBOBJS+=  ${LIBOBJDIR}stresep$U.o
LDADD+= 
USE_META?= yes
USE_FILEMON?= no
FILEMON_H?= no
BMAKE_PATH_MAX?= 1024
# used if MAXPATHLEN not defined
CPPFLAGS+= -DBMAKE_PATH_MAX=${BMAKE_PATH_MAX}
